name: Pacman

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile Java Classes
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
  TestPacManMove:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Classes
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --test TestPacManMove
  TestGhostMove:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Classes
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --test TestGhostMove
  TestMapGetLoc:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Classes
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --test TestMapGetLoc
